services:
  nginx:
    image: tiangolo/nginx-rtmp:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - streams-volumes:/hls/live
    ports:
      - "1935:1935"
  auth_server:
    build:
      dockerfile: ./Dockerfile
      context: .
    platform: linux/amd64
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "streamkeys"
    ports:
      - "5431:5432"
    volumes:
      - ./scripts/V1_init.sql:/docker-entrypoint-initdb.d/V1_init.sql
      - ./scripts/V2_stream_keys_populate.sql:/docker-entrypoint-initdb.d/V2_stream_keys_populate.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 30

volumes:
  streams-volumes:    
