services:
  nginx:
    image: tiangolo/nginx-rtmp:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - streams-volumes:/hls/live
    ports:
      - "1935:1935"
  auth_server:
    build:
      dockerfile: ./Dockerfile
      context: .
    platform: linux/amd64
    ports:
      - "8000:8000"

volumes:
  streams-volumes:    
